# -*- coding: utf-8 -*-
"""SPARK – Structure Parser, Alignment, and Reformatting Kit.ipynb

Automatically generated by Colab.
"""

"""## **1. PDB Aligner - Batch Structure & Sequence Matcher**"""

!pip install biopython

from Bio import SeqIO
from Bio import Align
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
import sys

def get_multiline_input(prompt_text):
    """Reads multi-line input from the user until an empty line is entered."""
    print(f"\n{prompt_text}")
    print("When you are done pasting, press ENTER on an empty line to finish:")
    lines = []
    while True:
        line = input()
        if not line.strip():
            break
        lines.append(line.strip())
    return "\n".join(lines)

def parse_user_sequence(raw_input):
    """Removes all spaces, tabs, and line breaks from the pasted text."""
    return "".join(raw_input.split())

def extract_pdb_record(pdb_file_path):
    """
    Extracts chains from a PDB file. 
    Detects multiple chains and warns the user interactively.
    """
    try:
        with open(pdb_file_path, 'r') as pdb_file:
            records = list(SeqIO.parse(pdb_file, 'pdb-atom'))
            
        if not records:
            print("  [!] No sequences found in this PDB.")
            return None
            
        # --- Multi-Chain Detection & Warning ---
        if len(records) > 1:
            chain_ids = [rec.id for rec in records]
            print(f"\n  ⚠️ WARNING: Multiple chains detected in this PDB: {chain_ids}")
            print("  This script aligns against the FIRST chain by default.")
            print("  If you need a specific chain, please use SPARK to convert your")
            print("  multi-chain PDB into a single chain and re-upload.")
            
            ans = input("\n  Do you want to proceed using ONLY the first chain? (y/n): ").strip().lower()
            if ans != 'y':
                print("  -> Skipping this PDB file. Please process it in SPARK first.")
                return None
                
        return records[0] # Return the first SeqRecord
    except Exception as e:
        print(f"  [!] Error reading {pdb_file_path}: {e}")
        return None

def print_colored_alignment(alignment_str):
    """Parses a Biopython pairwise alignment string and adds Green/Red ANSI colors."""
    GREEN = '\033[92m'
    RED = '\033[91m'
    RESET = '\033[0m'
    
    lines = alignment_str.strip().split('\n')
    i = 0
    while i < len(lines):
        target = lines[i]
        if not target.startswith("target"):
            print(target)
            i += 1
            continue
            
        match = lines[i+1]
        query = lines[i+2]
        
        c_target, c_match, c_query = "", "", ""
        
        # Find where the sequence starts to avoid coloring the header names/numbers
        seq_start_idx = 0
        for idx, char in enumerate(match):
            if char in ('|', '.'):
                seq_start_idx = idx
                break
        if seq_start_idx == 0: seq_start_idx = 15 
            
        # Walk back to the space so we don't chop a coordinate number in half
        while seq_start_idx > 0 and target[seq_start_idx-1] != ' ':
            seq_start_idx -= 1
            
        for idx, (t, m, q) in enumerate(zip(target, match, query)):
            # Skip coloring the labels (e.g., "target    0")
            if idx < seq_start_idx:
                c_target += t; c_match += m; c_query += q
                continue
                
            # Exact Match -> Green
            if m == '|':
                c_target += f"{GREEN}{t}{RESET}"
                c_match  += f"{GREEN}{m}{RESET}"
                c_query  += f"{GREEN}{q}{RESET}"
            # Mismatch or Gap -> Red
            elif m == '.' or (m == ' ' and (t == '-' or q == '-')) or (m == ' ' and t.isalpha() and q.isalpha()):
                c_target += f"{RED}{t}{RESET}"
                c_match  += f"{RED}{m}{RESET}"
                c_query  += f"{RED}{q}{RESET}"
            else:
                c_target += t; c_match += m; c_query += q
        
        print(c_target)
        print(c_match)
        print(c_query)
        print("")
        i += 4

def main_aligner():
    print("=" * 70)
    print(f"{'🔬 PDB ALIGNER: Batch Structure & Sequence Matcher':^70}")
    print("=" * 70)
    print("⚠️ IMPORTANT BIOLOGICAL WARNING ⚠️")
    print("Make sure you are not putting completely different proteins and")
    print("different sequences into this tool.")
    print("This workflow is strictly for checking isoforms, multiple PDB")
    print("structures of the SAME protein, or targeted mutations.")
    print("=" * 70)

    # --- 1. Collect PDB Files ---
    pdb_data = []
    while True:
        try:
            num_pdbs = int(input("\nHow many PDB files do you want to extract/check? "))
            if num_pdbs > 0: break
        except ValueError:
            print("Please enter a valid number.")

    for i in range(num_pdbs):
        print(f"\n--- PDB #{i+1} ---")
        name = input("Give a proper name for this PDB (e.g., 'GPX4_WildType'): ").strip()
        path = input(f"Enter the file path for {name} (e.g., 'P36969.pdb'): ").strip()
        
        record = extract_pdb_record(path)
        if record:
            seq_str = str(record.seq)
            pdb_data.append({"name": name, "path": path, "seq": seq_str, "record": record})
            print(f"  -> Successfully extracted {len(seq_str)} residues from {name}.")

    if not pdb_data:
        print("\nNo valid PDBs were loaded. Exiting tool.")
        return

    # --- 2. Checkpoint: Save FASTA ---
    print("\n" + "-" * 70)
    save_ans = input("Would you like to save the extracted PDB sequence(s) to a .fasta file? (y/n): ").strip().lower()
    if save_ans == 'y':
        out_name = input("Enter output filename (e.g., 'extracted_pdbs.fasta'): ").strip()
        if not out_name.endswith(".fasta"):
            out_name += ".fasta"
            
        records_to_save = [
            SeqRecord(Seq(item['seq']), id=item['name'], description="Extracted from PDB")
            for item in pdb_data
        ]
        try:
            with open(out_name, 'w') as out_file:
                SeqIO.write(records_to_save, out_file, 'fasta')
            print(f"✅ Successfully saved {len(records_to_save)} sequence(s) to {out_name}")
        except Exception as e:
            print(f"❌ Failed to save file: {e}")

    # --- 3. Checkpoint: Proceed to Alignment? ---
    print("\n" + "-" * 70)
    align_ans = input("Would you like to align these PDBs against user-provided sequences? (y/n): ").strip().lower()
    
    if align_ans != 'y':
        print("\nSequence extraction complete. Exiting tool. Have a great day!")
        return

    # --- 4. Collect FASTA Sequences ---
    seq_data = []
    while True:
        try:
            num_seqs = int(input("\nHow many raw sequences do you want to check against? "))
            if num_seqs > 0: break
        except ValueError:
            print("Please enter a valid number.")

    for i in range(num_seqs):
        print(f"\n--- Sequence #{i+1} ---")
        name = input("Give a proper name for this sequence (e.g., 'Isoform_2'): ").strip()
        raw_text = get_multiline_input(f"Paste ONLY the raw amino acid sequence for {name}:")
        
        clean_seq = parse_user_sequence(raw_text)
        if clean_seq:
            seq_data.append({"name": name, "seq": clean_seq.upper()})
            print(f"  -> Successfully loaded {len(clean_seq)} residues.")
        else:
            print(f"  -> No sequence detected for {name}. It will be skipped.")

    if not seq_data:
        print("\nNo valid sequences were loaded. Exiting.")
        return

    # --- 5. Perform Pairwise Alignments ---
    print("\n" + "=" * 70)
    print("1. RUNNING INDIVIDUAL PAIRWISE ALIGNMENTS...")
    print("=" * 70)
    
    pairwise_aligner = Align.PairwiseAligner()
    pairwise_aligner.mode = 'global'
    summary_stats = []

    for pdb in pdb_data:
        for user_seq in seq_data:
            print(f"\n### Aligning Target: [{pdb['name']}] vs Query: [{user_seq['name']}] ###")
            alignments = pairwise_aligner.align(pdb['seq'], user_seq['seq'])
            best_alignment = alignments[0]
            
            # Use the new colorized print function
            print_colored_alignment(str(best_alignment))
            
            max_len = max(len(pdb['seq']), len(user_seq['seq']))
            identity_pct = (best_alignment.score / max_len) * 100
            
            summary_stats.append({
                "pdb": pdb['name'], "seq": user_seq['name'],
                "pdb_len": len(pdb['seq']), "seq_len": len(user_seq['seq']),
                "score": best_alignment.score, "identity": identity_pct
            })
            print("-" * 70)

    # --- 6. Print the Statistical Summary Table ---
    print("\n" + "=" * 80)
    print(f"{'2. ALIGNMENT SUMMARY STATISTICS':^80}")
    print("=" * 80)
    print(f"{'Target PDB':<20} | {'Query Sequence':<20} | {'PDB Len':<7} | {'Seq Len':<7} | {'Score':<7} | {'Identity %':<10}")
    print("-" * 80)
    for stat in summary_stats:
        print(f"{stat['pdb']:<20} | {stat['seq']:<20} | {stat['pdb_len']:<7} | {stat['seq_len']:<7} | {stat['score']:<7.1f} | {stat['identity']:<9.2f}%")
    print("=" * 80 + "\n")

# Run the PDB Aligner
main_aligner()

"""## **.json to .pdb format from AI Prediction Model like Openfold2**"""

import json

def extract_pdb_from_json(json_filepath, output_pdb_filepath):
    """Extracts the PDB structure from the Boltz JSON file and saves it."""

    print(f"Reading JSON file: {json_filepath}...")

    # 1. Open and read the JSON envelope
    try:
        with open(json_filepath, "r") as f:
            data = json.load(f)
    except Exception as e:
        print(f"❌ Failed to read JSON: {e}")
        return

    # 2. Extract the structure string
    structure_string = None

    # Check for the key used in your specific file
    if "structures_in_ranked_order" in data:
        structure_string = data["structures_in_ranked_order"][0]["structure"]
    # Fallback to the standard key just in case
    elif "structures" in data:
        structure_string = data["structures"][0]["structure"]
    else:
        print("❌ Could not find the structure data inside the JSON.")
        return

    # 3. Save it directly as a PDB file!
    # (The string is already in PDB format, so no Biopython conversion is needed)
    try:
        with open(output_pdb_filepath, "w") as f:
            f.write(structure_string)
        print(f"✅ Success! Saved as: {output_pdb_filepath}")
    except Exception as e:
        print(f"❌ Failed to save PDB file: {e}")

# Run the extraction (Update filenames as needed)
# extract_pdb_from_json("Q9BV20.json", "Q9BV20.pdb")

"""## **.json to .pdb format from Boltz 2 (mmcif String)**"""

import json
from Bio.PDB import MMCIFParser, PDBIO

def convert_specific_boltz_json(json_filepath, output_pdb_filepath):
    print(f"Parsing {json_filepath}...")

    # 1. Load the JSON data
    with open(json_filepath, "r") as f:
        data = json.load(f)

    # 2. Extract the mmCIF structure block
    structure_text = data["structures"][0]["structure"]

    # 3. Write it out as a temporary .cif file
    temp_cif = "temp_output.cif"
    with open(temp_cif, "w") as f:
        f.write(structure_text)

    print("Structure extracted. Translating mmCIF format to PDB...")

    # 4. Read it as mmCIF and save as clean PDB
    try:
        parser = MMCIFParser(QUIET=True)
        structure = parser.get_structure("protein_structure", temp_cif)

        io = PDBIO()
        io.set_structure(structure)
        io.save(output_pdb_filepath)
        print(f"✅ Success! Your file is ready at: {output_pdb_filepath}")

    except Exception as e:
        print(f"❌ Conversion failed: {e}")

    finally:
        # Clean up the temporary .cif file automatically
        import os
        if os.path.exists(temp_cif):
            os.remove(temp_cif)

# Execute the conversion (Update filenames as needed)
# convert_specific_boltz_json("Q9BV20.json", "Q9BV20.pdb")

"""## **.mmcif to .pdb format from RSCB PDB Database**"""

from Bio.PDB import MMCIFParser, PDBIO

# 1. Load the CIF file
parser = MMCIFParser()
structure = parser.get_structure("4LDR", "4LDR.cif")

# 2. Save it as a PDB file
io = PDBIO()
io.set_structure(structure)
io.save("4LDR.pdb")

print("Conversion complete!")

"""## **Difference between different .pdb structure**"""

import os
import pandas as pd
import glob
import numpy as np
from Bio.PDB import PDBParser, Superimposer

def calculate_rg(atoms):
    """Calculates the Radius of Gyration from a list of Biopython atoms."""
    coords = np.array([atom.get_coord() for atom in atoms])
    center_of_mass = coords.mean(axis=0)
    rg = np.sqrt(np.sum((coords - center_of_mass)**2) / len(coords))
    return round(rg, 2)

def generate_ultimate_table(directory=".", reference_pdb="Q9BV20.pdb"):
    pdb_files = glob.glob(os.path.join(directory, "*.pdb"))
    parser = PDBParser(QUIET=True)

    # Load reference structure for RMSD calculation
    try:
        ref_structure = parser.get_structure("ref", os.path.join(directory, reference_pdb))
        ref_ca = [atom for atom in ref_structure[0]['A'].get_atoms() if atom.get_name() == 'CA']
    except:
        ref_ca = None
        print(f"⚠️ Could not load reference {reference_pdb} for RMSD calculations.")

    results = []

    for filepath in pdb_files:
        filename = os.path.basename(filepath)

        # --- 1. Basic Metrics (Text Parsing) ---
        chains = set()
        residues = set()
        atom_count = 0
        hetatm_count = 0
        b_factors = []

        with open(filepath, 'r') as f:
            for line in f:
                if line.startswith("ATOM"):
                    atom_count += 1
                    if len(line) > 21:
                        chains.add(line[21])
                    if len(line) > 26:
                        res_num = line[22:26].strip()
                        chain_id = line[21]
                        residues.add(f"{chain_id}_{res_num}")
                    if len(line) > 66:
                        try:
                            b_factors.append(float(line[60:66].strip()))
                        except ValueError:
                            pass
                elif line.startswith("HETATM"):
                    hetatm_count += 1

        avg_bfactor = sum(b_factors) / len(b_factors) if b_factors else 0

        # --- 2. Advanced Metrics (Biopython Parsing) ---
        rg = "N/A"
        rmsd_val = "N/A"
        structure = parser.get_structure(filename, filepath)

        try:
            model = structure[0]
            chain_A = model['A']

            # Calculate Radius of Gyration (Heavy atoms only)
            heavy_atoms = [atom for atom in chain_A.get_atoms() if atom.element != 'H']
            rg = calculate_rg(heavy_atoms)

            # Calculate RMSD
            if ref_ca and filename != reference_pdb:
                target_ca = [atom for atom in chain_A.get_atoms() if atom.get_name() == 'CA']
                ref_res_ids = [atom.get_parent().get_id()[1] for atom in ref_ca]
                target_ca_matched = [atom for atom in target_ca if atom.get_parent().get_id()[1] in ref_res_ids]

                if len(ref_ca) == len(target_ca_matched):
                    superimposer = Superimposer()
                    superimposer.set_atoms(ref_ca, target_ca_matched)
                    rmsd_val = round(superimposer.rms, 2)
                else:
                    rmsd_val = "Mismatch"
        except KeyError:
            pass # Skip advanced math if Chain A is missing

        # --- 3. Combine into final row ---
        results.append({
            "File / Model": filename,
            "Chains": ", ".join(sorted(list(chains))) if chains else "None",
            "Total Residues": len(residues),
            "Total Atoms": atom_count,
            "HETATM": hetatm_count,
            "Avg Score/B-Factor": round(avg_bfactor, 2),
            "Radius of Gyration (Å)": rg,
            "RMSD to PDB (Å)": rmsd_val if filename != reference_pdb else "0.0 (Reference)"
        })

    df = pd.DataFrame(results).sort_values(by="File / Model").reset_index(drop=True)
    return df

# Run the master analysis (Update reference_pdb as needed)
# ultimate_table = generate_ultimate_table()
# display(ultimate_table)

"""## **H and HOH View with PDB Structure**"""

!pip install py3Dmol
import py3Dmol

# --- 1. Read and Parse the PDB for Counts ---
with open("/content/4ldr.pdb", "r") as f:
    pdb_data = f.read()

# Variables to store our counts
h_atoms = 0
water_residues = set()

for line in pdb_data.split('\n'):
    if line.startswith(("ATOM", "HETATM")):
        res_name = line[17:20].strip()
        chain_id = line[21]
        res_seq = line[22:26].strip()

        # Extract the element symbol (Standard PDB format stores this in columns 77-78)
        element = line[76:78].strip() if len(line) >= 78 else line[12:16].strip()[0]
        if element == 'H':
            h_atoms += 1

        # Track unique water molecules by their Chain + Residue Number
        if res_name in ['HOH', 'WAT']:
            water_residues.add(f"{chain_id}_{res_seq}")

water_count = len(water_residues)

print("📊 STRUCTURE STATISTICS:")
print(f"Total Hydrogen (H) Atoms: {h_atoms}")
print(f"Total Water (H2O) Molecules: {water_count}")
print("-" * 40)

# --- 2. Py3Dmol Visualization ---
print("🔍 2x2 Synchronized Grid (Dark Mode)")
print("Top-Left: Clean (No Water, No H)      | Top-Right: With Water, No H")
print("Bottom-Left: With H, No Water         | Bottom-Right: With Water, With H")

# Initialize a 2x2 grid
view = py3Dmol.view(viewergrid=(2, 2), linked=True, width=900, height=800)
view.setBackgroundColor('black')

# Load the same model into all 4 grid viewers
for r in range(2):
    for c in range(2):
        view.addModel(pdb_data, "pdb", viewer=(r, c))
        # Clear any default styles first
        view.setStyle({'viewer': (r, c)}, {})

# Helper function to apply our custom styles
def apply_styles(r, c, show_water, show_hydrogens):
    chain_colors = ['cyan', 'lime', 'yellow', 'magenta', 'orange', 'white']
    chain_ids = ['A', 'B', 'C', 'D', 'E', 'F']

    for i, chain in enumerate(chain_ids):
        # FIX: Changed setStyle to addStyle!
        view.addStyle(
            {'chain': chain},
            {'cartoon': {'color': chain_colors[i]}},
            viewer=(r, c)
        )

    # --- HYDROGENS (Protein) ---
    if show_hydrogens:
        view.addStyle(
            {'elem': 'H', 'resn': ['HOH', 'WAT'], 'invert': True},
            {'sphere': {'color': 'yellow', 'radius': 0.25}},
            viewer=(r, c)
        )

    # --- WATER (HOH) ---
    if show_water:
        view.addStyle(
            {'resn': ['HOH', 'WAT'], 'elem': 'O'},
            {'sphere': {'color': 'red', 'radius': 0.6}},
            viewer=(r, c)
        )
        if show_hydrogens:
            view.addStyle(
                {'resn': ['HOH', 'WAT'], 'elem': 'H'},
                {'sphere': {'color': 'yellow', 'radius': 0.35}},
                viewer=(r, c)
            )

# Apply the styles to each quadrant
apply_styles(0, 0, show_water=False, show_hydrogens=False)
apply_styles(0, 1, show_water=True, show_hydrogens=False)
apply_styles(1, 0, show_water=False, show_hydrogens=True)
apply_styles(1, 1, show_water=True, show_hydrogens=True)

view.zoomTo()
view.show()

"""## **Remove H2O (Water) from pdb**"""

def remove_water_from_pdb(input_filepath, output_filepath):
    """Removes all HOH (water) molecules from a PDB file."""

    with open(input_filepath, 'r') as infile, open(output_filepath, 'w') as outfile:
        count = 0
        for line in infile:
            # If the line represents an atom and belongs to HOH, skip it
            if line.startswith("HETATM") and "HOH" in line:
                count += 1
                continue

            # Otherwise, keep the line
            outfile.write(line)

    print(f"✅ Removed {count} water atoms.")
    print(f"✅ Saved clean protein to: {output_filepath}")

# Run the function on your experimental file
remove_water_from_pdb("/content/4ldr.pdb", "/content/4ldr_clean.pdb")

"""## **Visualization of Raw & Clean PDB Structure**"""

import py3Dmol

# --- 1. Helper Function to Count Atoms ---
def count_h_and_water(pdb_text):
    """Parses PDB text and returns the count of H atoms and unique H2O molecules."""
    h_atoms = 0
    water_residues = set()

    for line in pdb_text.split('\n'):
        if line.startswith(("ATOM", "HETATM")):
            res_name = line[17:20].strip()
            chain_id = line[21] if len(line) > 21 else ' '
            res_seq = line[22:26].strip() if len(line) > 26 else ' '

            # Extract the element symbol (Standard PDB format columns 77-78)
            element = line[76:78].strip() if len(line) >= 78 else line[12:16].strip()[0]
            if element == 'H':
                h_atoms += 1

            # Track unique water molecules by their Chain + Residue Number
            if res_name in ['HOH', 'WAT']:
                water_residues.add(f"{chain_id}_{res_seq}")

    return h_atoms, len(water_residues)

# --- 2. Read Files and Calculate Statistics ---
with open("/content/4ldr.pdb", "r") as f:
    pdb_before = f.read()

with open("/content/4ldr_clean.pdb", "r") as f:
    pdb_after = f.read()

# Get counts
h_before, w_before = count_h_and_water(pdb_before)
h_after, w_after = count_h_and_water(pdb_after)

# Print the comparison
print("📊 STRUCTURE STATISTICS:")
print(f"BEFORE (4ldr.pdb)        -> Hydrogens: {h_before} | Water (H2O): {w_before}")
print(f"AFTER  (4ldr_clean.pdb) -> Hydrogens: {h_after} | Water (H2O): {w_after}")
print("-" * 60)

# --- 3. Py3Dmol Visualization ---
print("🔍 Synchronized Comparison (Dark Mode)")
print("Left: BEFORE (With Water & H) | Right: AFTER (Cleaned, H Retained)")

# Initialize a 1x2 side-by-side grid with synchronized zooming
view = py3Dmol.view(viewergrid=(1, 2), linked=True, width=900, height=500)
view.setBackgroundColor('black')

# Load the models into the viewers
view.addModel(pdb_before, "pdb", viewer=(0, 0)) # Left
view.addModel(pdb_after, "pdb", viewer=(0, 1))  # Right

# Apply Styles (Chains & Hydrogens)
chain_colors = ['cyan', 'lime', 'yellow', 'magenta', 'orange', 'white']
chain_ids = ['A', 'B', 'C', 'D', 'E', 'F']

# Loop through both viewers (0,0 is left, 0,1 is right)
for r, c in [(0, 0), (0, 1)]:
    view.setStyle({'viewer': (r, c)}, {})

    # Color distinct chains
    for i, chain in enumerate(chain_ids):
        view.addStyle(
            {'chain': chain},
            {'cartoon': {'color': chain_colors[i]}},
            viewer=(r, c)
        )

    # Layer the Hydrogen atoms as smaller white spheres on BOTH viewers
    view.addStyle(
        {'elem': 'H'},
        {'sphere': {'color': 'white', 'radius': 0.3}},
        viewer=(r, c)
    )

# Add the red spheres for water oxygen ONLY to the left viewer
view.addStyle(
    {'resn': 'HOH', 'elem': 'O'},
    {'sphere': {'color': 'red', 'radius': 0.8}},
    viewer=(0, 0)
)

# Render the synchronized view
view.zoomTo()
view.show()

"""## **Universal Extraction of Chain of Interest**"""

def universal_chain_extractor(input_filepath, output_filepath, target_chain='A'):
    """
    Extracts any specified chain from a PDB file safely in a single pass.
    Handles standard letters, lowercase, numbers, or blank chains.
    """
    # If the user wants a blank chain, search for a space character
    if target_chain == '' or target_chain is None:
        target_chain = ' '

    atom_count = 0

    with open(input_filepath, 'r') as infile, open(output_filepath, 'w') as outfile:
        for line in infile:
            # 1. Copy standard file headers as we encounter them
            if line.startswith(("HEADER", "TITLE", "COMPND", "REMARK")):
                outfile.write(line)
                continue  # Move to the next line immediately

            # 2. Check for structural and coordinate lines
            if line.startswith(("ATOM", "HETATM", "ANISOU", "TER")):
                # Ensure the line is long enough to contain the chain ID (column 22 / index 21)
                if len(line) > 21:
                    current_chain = line[21]
                    if current_chain == target_chain:
                        outfile.write(line)
                        if line.startswith(("ATOM", "HETATM")):
                            atom_count += 1
                # Handle edge-case TER lines that might be truncated short but belong to our chain
                elif line.startswith("TER") and atom_count > 0:
                    outfile.write(line)

        # Always write a clean END tag at the very bottom of the new PDB file
        outfile.write("END\n")

    if atom_count == 0:
        print(f"⚠️ Warning: No atoms found for Chain '{target_chain}'. Check if the file uses a different ID or a blank space.")
    else:
        print(f"✅ Successfully extracted Chain '{target_chain}' ({atom_count} atoms) -> {output_filepath}")

# --- EXECUTE THE FUNCTION ---
# This will extract chain 'A' from your SwissModel file and save it in your /content/ folder
# universal_chain_extractor(
#     input_filepath="/content/Q9BV20_swissmod.pdb",
#     output_filepath="/content/Q9BV20_swissmod_A.pdb",
#     target_chain="A"
# )

"""## **Remove All Hydrogen**"""

def remove_hydrogens(input_filepath, output_filepath):
    """Removes all Hydrogen (H) atoms from a PDB file."""

    with open(input_filepath, 'r') as infile, open(output_filepath, 'w') as outfile:
        atom_count = 0
        hydrogen_count = 0

        for line in infile:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                # In PDB format, the element symbol is usually in columns 77-78
                # But a safer way is to check the atom name starting character
                atom_name = line[12:16].strip()
                if atom_name.startswith('H') or (len(line) > 77 and line[76:78].strip() == 'H'):
                    hydrogen_count += 1
                    continue # Skip this line
                else:
                    atom_count += 1

            outfile.write(line)

    print(f"✅ Removed {hydrogen_count} Hydrogen atoms.")
    print(f"✅ Remaining Heavy Atoms: {atom_count}")
    print(f"✅ Saved to: {output_filepath}")

# Run it on your experimental file
# remove_hydrogens("Q9BV20.pdb", "Q9BV20_no_hydrogens.pdb")

"""## **Comparison & Visualuzation of Different Structure:**"""

import py3Dmol
import glob
import os
import math

def create_linked_viewer_dark(directory="."):
    # 1. Find and count all .pdb files
    pdb_files = sorted(glob.glob(os.path.join(directory, "*.pdb")))
    num_files = len(pdb_files)

    if num_files == 0:
        print("❌ No .pdb files found in the current directory.")
        return

    print(f"✅ Found {num_files} PDB files. Building dark-mode viewer...")

    cols = math.ceil(math.sqrt(num_files))
    rows = math.ceil(num_files / cols)

    # 2. Create the grid
    view = py3Dmol.view(viewergrid=(rows, cols), linked=True, width=1000, height=400 * rows)

    # 🌟 NEW: Set the global background color to black
    view.setBackgroundColor('black')

    print("\n--- Grid Layout Guide ---")

    for i, filepath in enumerate(pdb_files):
        filename = os.path.basename(filepath)
        row = i // cols
        col = i % cols

        print(f"Window (Row {row}, Col {col}): {filename}")

        with open(filepath, 'r') as f:
            pdb_data = f.read()

        view.addModel(pdb_data, 'pdb', viewer=(row, col))
        view.setStyle({'cartoon': {'color': 'spectrum'}}, viewer=(row, col))
        view.zoomTo(viewer=(row, col))

    print("-" * 25)
    view.show()

# Run the dark-mode viewer
# create_linked_viewer_dark()
